version: '3.8'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=1234
      - POSTGRESQL_DATABASE=pms
    networks:
      - app_network
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: node:18
    working_dir: /app
    volumes:
      - ./api:/app 
    command: npm start
    environment:
      DATABASE_URL: postgres://postgres:1234@postgresql:5432/pms
    depends_on:
      - postgresql
    networks:
      - app_network
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:
    driver: local 

networks:
  app_network:
    driver: bridge
